"""Export the stock COCO yolo26n into the app's model contract, for testing.

The trained litter model is the real thing; this is what you run the app
against before it exists. COCO has no litter classes, but it does have bottles,
cups, cutlery and fruit lying around, which is close enough to exercise the
whole camera -> detect -> rarity -> reward path with real detections.

    pip install ultralytics onnx onnxslim onnx2tf ai_edge_litert tensorflow tf_keras
    python ml/export_stock_yolo26n.py

Writes into mobile/assets/models/:
    coco_yolo26n.tflite   same tensor contract as ecoquest_yolo26n.tflite
    coco_labels.json      COCO ids mapped onto EcoQuest's taxonomy

Then run the app against it:

    flutter run --dart-define=ECOQUEST_LABELS=assets/models/coco_labels.json

Nothing else changes: `LabelSet` reads the weights filename out of the label
file, and looks classes up by their declared `id`, so a label file that covers
only some of a model's 80 classes simply drops the rest.
"""

import json
import shutil
from pathlib import Path

from export_tflite import ASSETS, IMGSZ, export, probe

WEIGHTS = "yolo26n.pt"  # downloaded on first use

# Same per-class economy the notebook ships, keyed by EcoQuest class name.
CLASS_META = {
    "plastic": {"points": 3, "bin": "plastic", "co2_g": 40},
    "glass": {"points": 4, "bin": "glass", "co2_g": 70},
    "metal": {"points": 5, "bin": "metal", "co2_g": 150},
    "paper": {"points": 2, "bin": "paper", "co2_g": 20},
    "cigarette": {"points": 4, "bin": "general", "co2_g": 5},
    "other_litter": {"points": 2, "bin": "general", "co2_g": 15},
}

# COCO class id -> the EcoQuest class it stands in for. Everything not listed
# here (people, cars, dogs, sofas) is dropped by the app, which is the point:
# pointing the camera at a room should not hand out XP.
COCO_TO_ECOQUEST = {
    39: "plastic",       # bottle
    40: "glass",         # wine glass
    41: "plastic",       # cup
    42: "metal",         # fork
    43: "metal",         # knife
    44: "metal",         # spoon
    45: "other_litter",  # bowl
    46: "other_litter",  # banana  (peel)
    47: "other_litter",  # apple   (core)
    48: "other_litter",  # sandwich
    49: "other_litter",  # orange
    73: "paper",         # book
    76: "metal",         # scissors
}


def main() -> None:
    # Same converter and same contract gate the trained model goes through, so
    # the two label files can never disagree about the coordinate space.
    tflite = export(Path(WEIGHTS), IMGSZ)
    out_shape, normalized = probe(tflite, IMGSZ)

    ASSETS.mkdir(parents=True, exist_ok=True)
    shutil.copy(tflite, ASSETS / "coco_yolo26n.tflite")
    (ASSETS / "coco_labels.json").write_text(
        json.dumps(_labels(out_shape, normalized), indent=2) + "\n", encoding="utf-8"
    )
    print(f"\nwrote {ASSETS / 'coco_yolo26n.tflite'} and coco_labels.json")
    print(
        "run: flutter run "
        "--dart-define=ECOQUEST_LABELS=assets/models/coco_labels.json"
    )


def _labels(out_shape: list[int], normalized: bool) -> dict:
    from ultralytics import YOLO

    names = YOLO(WEIGHTS).names
    return {
        "_comment": (
            "STOCK COCO yolo26n, for testing only. Generated by "
            "ml/export_stock_yolo26n.py. `id` is the COCO output index; the "
            "app looks classes up by it, so the 67 unmapped COCO classes are "
            "silently ignored. Not for release — the metrics below are COCO's, "
            "not litter's."
        ),
        "model": "coco_yolo26n.tflite",
        "arch": "yolo26n",
        "imgsz": IMGSZ,
        "nms_free": True,
        "input": {
            "shape": [1, IMGSZ, IMGSZ, 3],
            "dtype": "float32",
            "range": "0..1",
            "letterbox_fill": [114, 114, 114],
        },
        "output": {
            "shape": out_shape,
            "layout": ["x1", "y1", "x2", "y2", "conf", "class"],
            "coords": "normalized 0..1"
            if normalized
            else f"pixels in letterboxed {IMGSZ}x{IMGSZ}",
            "sorted_by_conf": True,
        },
        # Higher than the trained model's 0.35: COCO fires on everything, and a
        # test build that detects a "bottle" in a curtain fold is not testing much.
        "conf_threshold": 0.45,
        "metrics": {"map50": 0.0, "map50_95": 0.0},
        "classes": [
            {
                "id": coco_id,
                "name": name,
                "coco": names[coco_id],
                **CLASS_META[name],
            }
            for coco_id, name in sorted(COCO_TO_ECOQUEST.items())
        ],
    }




if __name__ == "__main__":
    main()
